### ISSUE TITLE
HackTX domain seems to have expired/been hacked

### ISSUE THREAD

**Issue by jamietanna** [hacktx/nucleus#22]
I've been interested in trying out Nucleus, and by attempting to view the current site, https://my.hacktx.com/, I get an SSL error, followed by a redirect to a site that doesn't look quite correct:
![2016-01-14-093950_758x435_scrot](https://cloud.githubusercontent.com/assets/3315059/12320841/ceaace1e-baa2-11e5-9a09-0bbbd0e7ffa4.png)

**Comment by ThomasGaubert** [comment]
The HackTX instance of Nucleus was shut down after the event to save on costs. Unfortunately, we don't have any other running instances at this time.

In the near future we'll set up a landing page at http://my.hacktx.com to avoid the SSL error.

**Comment by rob0rt** [comment]
@ThomasGaubert is correct; what likely happened is whatever we have our DNS pointed at got taken when we killed our server after HackTX, and their SSL cert doesn't match my.hacktx.com (which it shouldn't).

Seems like a quick fix but is unrelated to the Nucleus project itself.
